### ISSUE TITLE
PR 라벨 깃헙 액션으로 자동화 해 보기

### ISSUE THREAD

**Issue by nattybear** [YunWonYong/Programmers#142]
* [우리 저장소 라벨 룰 위키](https://gist.github.com/nattybear/33ff6ef48108c389a0b8252059312ebe)

## 진행 상황
- [x] fork
- [x] 개발용 branch 만들기 `action`
- [x] 깃헙 액션 이해
- [x] 서버 구축
- [x] 라벨 생성 스크립트 작성
- [x] 구현
- [x] 테스트
- [x] PR
- [x] 드래프트 해보기
- [x] 스크립트에서 패스워드 분리하고 스크립트 커밋하기
- [ ] merge

## 구현해야 하는 상세 기능
- [x] PR 오픈 되었을 때 `approve` 달기
- [x] 리뷰어 지정 되었을 때 리뷰어 이름 라벨 달기
- [x] 리뷰어 지정 취소했을 때 리뷰어 이름 라벨 빼기
- [x] 리뷰 제출 되었을 때 리뷰어 이름 라벨 빼기
- [x] 모든 리뷰어가 리뷰 제출 했을 때 `approve` 라벨 빼고 `merge` 라벨 달기
- [x] merge가 완료되고 PR이 닫히면 `merge` 라벨 빼기

## 파악해야 하는 이벤트 종류
- [x] PR이 생성되었을 때 `opened`
- [x] 리뷰어가 지정되었을 때 `review_requested`
- [x] 개별 리뷰가 완료되었을 때 `submitted`
- [x] 머지가 되었을 때 `closed`

## 참고 문서
* ~~[PR 리뷰 요청하기 API](https://docs.github.com/en/rest/reference/pulls#request-reviewers-for-a-pull-request)~~
* [깃헙 액션 문서](https://docs.github.com/en/actions/learn-github-actions)
* [깃헙 액션 이해하기](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions)
* [PR 이벤트](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request)
* [PR API](https://docs.github.com/en/rest/reference/pulls#check-if-a-pull-request-has-been-merged)
* [라벨 API](https://docs.github.com/en/rest/reference/issues#labels)
* ~~[Node.js에서 HTTP POST 요청하기](https://nodejs.dev/learn/make-an-http-post-request-using-nodejs)~~

**Comment by nattybear** [comment]
fork한 저장소에서는 이슈를 만들 수가 없네요 ㅎ

**Comment by nattybear** [comment]
~~크리스마스 아침에 내가 뭐 하는 거야...ㅋ~~

**Comment by nattybear** [comment]
> For example, you can run a workflow to automatically add the appropriate labels whenever someone creates a new issue in your repository.

**Comment by YunWonYong** [comment]
화이팅화이팅!! ㅎㅎ

**Comment by nattybear** [comment]
깃헙 액션 워크플로우 파일을 커밋하려면 personal access token scope에 `workflow`를 선택해야 함

**Comment by nattybear** [comment]
깃헙에서 호스팅 하는 액션 실행용 인스턴스이는 기본으로 `node`가 설치되어 있음

**Comment by nattybear** [comment]
액션에서 내가 만든 코드를 사용하려면 아래처럼 키워드 `uses`를 먼저 선언해야 함

```yaml
steps:
  - uses: actions/checkout@v2
```

**Comment by nattybear** [comment]
JavaScript에서 문자열을 json 객체로 변환하려면 아래와 같이 한다.

```javascript
JSON.parse(yourJsonString)
```

[In Node.js, how do I turn a string to a json?](https://stackoverflow.com/questions/5801699/in-node-js-how-do-i-turn-a-string-to-a-json)

**Comment by nattybear** [comment]
personal access token 하나로 저장소 코드 커밋과 라벨 생성 API를 동시에 할 수 없음

**Comment by nattybear** [comment]
자체 서버 액션 실행 경로는 아래와 같음

```
/home/vincent/actions-runner/_work/Programmers/Programmers
```

**Comment by nattybear** [comment]
리뷰어 수가 하나일 때와 여러 명일 경우 필드 타입이 다름

값을 가져오기 전에 검사를 먼저 해야 함

**Comment by nattybear** [comment]
리뷰어 지정 이벤트는 여러명을 지정하더라도 각각 따로 발생함

**Comment by nattybear** [comment]
아래 테스트에서 발견된 이슈가 있습니다.

* https://github.com/nattybear/Programmers/pull/69
* https://github.com/nattybear/Programmers/pull/70

이슈는 리뷰어가 리뷰를 제출하지 않았는데 PR 요청자가 리뷰어를 철회할 경우에는 `approve`가 없어지지 않고 `merge`도 붙지 않는 것입니다.

또 하나는 모든 리뷰어가 리뷰를 제출하지 않았는데 요청자가 merge를 하는 경우에도 `approve`가 없어지지 않습니다.

아래와 같이 정상적인 흐름을 타게 되는 경우에는 문제가 생기지는 않습니다만 나중에 누군가 이슈를 따로 등록 해 주시면 버그 픽스 해보겠습니다 ㅎ
