### ISSUE TITLE
승인 최소 인원 수

### ISSUE THREAD

**Issue by nattybear** [YunWonYong/Programmers#159]
현재 PR 최소 승인 인원 수가 4명인 것 같습니다. 2명으로 하기로 했던 것 같은데, 다시 4명으로 바뀌었나요?

**Comment by YunWonYong** [comment]
![A4A93BF4-C31A-42AA-B4E1-5E2B2BA696F8](https://user-images.githubusercontent.com/59129553/148211732-31bfab45-fa14-4958-b657-ebf665b824c5.png)
4명이었네요

수정했습니다 :)
