### ISSUE TITLE
숫자 문자열과 영단어

### ISSUE THREAD

**Issue by YunWonYong** [YunWonYong/Programmers#44]
||ywy|andy|nattybear|
|:---:|:-------:|:-------:|:-------:|
|JAVA|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|
|JS|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|
|C++|||

**Comment by nattybear** [comment]
이건 열심히 풀고 있습니다 ㅎ 내일 새벽 내로 한번 해볼게요 ㅎ
