### ISSUE TITLE
PR을 문제별로 구분할 수 없음

### ISSUE THREAD

**Issue by nattybear** [YunWonYong/Programmers#56]
## 현황
* 유저별로 브랜치 구분
* 소스코드 디렉토리도 유저별로 구분
* 2명 이상의 승인이 있어야 병합 가능

## 문제
* 이전에 요청한 PR이 아직 병합되지 않은 상태에서 새로운 push를 할 경우 앞선 PR에 반영되어 버림
* 문제별로 PR을 구분할 수 없음

## 해결
* 유저별이 아니라 문제별로 브랜치 구분

**Comment by YunWonYong** [comment]
문제별로 브랜치를 구성해서 PR할 경우 소스 총동기능성이 높아 일부러 유저별로한거고 마스터 브랜치를 워킹디렉토리로 pull 안할라고 브랜치를 계정별로 만겁니다. 간단히 저는 저의 브랜치인 ywy 브랜치만 형상유지하면 다른 사람의 소스에 영향 안받을 수 있는데 예를 들면 마스터브랜치와 형상유지하면 제가 설정한 jdk1.8에서 지원 안하는 repeat와 같은 함수 때문에 컴파일 할때 항상 컴펌창이 발생하는 상황을 막을 수 있죠 그리고 이슈는 상의하시고 만드셨으면 좋겠습니다.

**Comment by nattybear** [comment]
* 이미 유저별로 디렉토리가 구분되어 있기 때문에 유저별로 브랜치를 구분하지 않아도 소스코드가 충돌하지 않습니다.
* 프로그래머스 Java 컴파일러 버전은 `OpenJDK 14.0.2`입니다.
* PR을 승인하시기 전에 브랜치에서 컴파일 성공 여부를 테스트 하시고 문제가 없다고 판단이 되시면 승인하시면 됩니다.
* 이슈를 등록할 때 왜 별도 상의가 필요한가요?

**Comment by YunWonYong** [comment]
제가 기획한 내용을 모르시고 이슈만드는것보다 제가 어떤 생각으로 이렇게 기획했는지 먼저 물어보시고 이슈 만들어도 안늦을꺼 같습니다. 프로그래머스에서 jdk14라고 하더라고 각자 로컬에 맞는 jdk에서 코딩할텐데 환경 설정할 줄 알면 상관없지만 모르면 시간을 투자해야하니 그렇고 소스코드가 충돌 안난다는 보장을 못합니다. 저희 3명에서 진행하니 괜찮을지 몰라도 사람이 많아지면 그것 또한 문제 가능성이 높죠 각자 알아서 해결하면 상관없지만요.
그리고 협업하는거니 이슈 만들기전 상의하는건 당연하다 생각됍니다.

**Comment by nattybear** [comment]
* 유저별로 브랜치를 구분한다고 해서 소스코드 충돌을 막을 수 없습니다. 지금도 제가 원영님의 소크코드를 변경한 PR을 날릴 수 있습니다. 소스코드 충돌을 방지할 수 있게 하는 것은 리뷰어가 PR `거절`을 선택하는 것입니다.
* 유저가 3명이든 100명이든 지금처럼 유저별로 디렉토리를 구분하고 각자 자신의 디렉토리만 수정한다는 규칙이 있다면 소스코드가 충돌할 일은 없습니다.
* 이슈를 생성하고 의견을 교환하는 과정 자체가 협업이라고 생각합니다. 그런 면에서 개발자가 아닌 제가 이렇게 깃헙을 통해서 다른 분과 코드와 운영과 설계에 대한 의견을 교환할 기회를 주셔서 너무 감사하고요.
* 말씀하신대로 각자 로컬에 설치한 JDK의 버전이 다르므로 기준이 필요합니다. 프로그래머스의 컴파일러 버전이 기준이 되는 것이 좋다고 생각합니다.

**Comment by YunWonYong** [comment]
이슈는 의견을 공유하는게 아니고 회의를 통해 나온 문제점을 정리해서 해결해야 하는 방법들과 일정 또는 당담자을 명시해놓는거라 생각합니다. jdk의 버전을 통일하면 js도 통일해야하는거 아닙니까? 그럼 es6나 es5로 통일해야하는게 굳이 그게 의미가 있나요? 유저별로 브랜치를 나눠 놓으면 마스터 브랜치를 pull 하지 않는 이상 본인의 패키지만 있어서 jdk버전도 통일할 필요도 없는데 의견을 말씀해주시는건 좋지만 현재 상황도 이해해주셨으면 좋겠습니다.

**Comment by nattybear** [comment]
* 이슈의 활용 범위를 그렇게 생각하신다면 따르겠습니다.

* 컴파일러 버전은 프로그래머스에서 지원하는 버전이 하위 호환을 지원해주는 범위라면 무엇을 사용해도 상관 없다고 생각합니다. 따라서 유저가 어떤 언어로 어떤 버전을 사용하든지 상관이 없습니다.

* 컴파일러의 버전이 여기서 이슈가 된 이유는 원영님의 로컬 버전이 JDK8이며 JDK8가 지원하지 않는 `repeat` 같은 함수를 사용할 경우 원영님의 로컬에서 컴파일 관련 경고창이 뜬다고 말씀하셨기 때문입니다.

* 브랜치를 문제별로 하는 것이 어떨지 의견을 제시한 것입니다. 저 혼자 하는 것이 아니므로 다른 사람의 동의가 없다면 강행할 이유가 없습니다. 현행을 따르겠습니다. 다만 모두 깃헙 활용을 공부하는 입장에서 다양한 시도를 해보는 것도 좋을 것 같습니다.

**Comment by YunWonYong** [comment]
네 알겠습니다. 
다만 제가 저의 의견을 따라달라 말씀드린게 아니고 전 이러한 생각을 갖고 있이고 제가 무슨 이유로 저런 생각하는지 이해해주셨으면 하는 바램에 말씀드린거고 사실 정확히 말하면 준규님이 제시한 방법이 정설입니다. 이슈 한개에 여러개의 pr들이 있고 각각의 pr에 매칭되는 브랜치들 있는게 정설입니다. 다만 제가 이렇게 안하는 이유는 깃허브가 익숙한 사람이 있는 반면 어려워하는 사람도 있으니 심플하게 할려고 했습니다. 좋은 의견 감사합니다. 제가 준규님의 제안을 테스트해보겠습니다.

**Comment by YunWonYong** [comment]
제가 테스트하고 준규님이 확인하신 후 이슈 닫겠습니다.

**Comment by YunWonYong** [comment]
- 테스트환경
1. 컴퓨터 2대 필요
2. 계정 2개 필요
3. 테스트 브랜치 한 개 필요

- 테스트시나리오
1. 본계정과 부계정을 협업 상태로 만든다.
2. 테스트 하기 위한 브랜치(branchTest)의 스냅샷을 본계정과 부계정에 clone 또는 pull 한다.
3. 본계정에서 파일을 생성 후 push를 한다.
![1](https://user-images.githubusercontent.com/59129553/139677846-dc164b27-b2a7-408f-a475-28a301f6b2eb.png)
4. 부계정은 pull을 안한 상태에서 본계정 처럼 파일을 생성 후 push를 시도한다.
![2](https://user-images.githubusercontent.com/59129553/139678031-be90f58c-0b24-4603-ae96-3940276a3e5a.png)    
(관점은 본계정이 push한 상태의 스냅샷을 부계정이 반영하지 않아 branchTest의 스냅샷을 pull 하라는 소리)    

- 테스트를 통한 예시의 결론
1. 문제당 브랜치를 만들면 작업 전 항상 pull 작업을 선행 해야 한다.
2. 작업 시작 전에 pull 작업을 했어도 시차에 따라 push하기 전 형상이 일치 한지 확인한 후 push해야 한다.
3. 일주일에 문제는 3개인데 항상 pull작업 후 push 작업을 3번 해야 한다.

**Comment by YunWonYong** [comment]
준규님 테스트 보셨나요? 피드백 부탁드립니다:)

**Comment by nattybear** [comment]
* 로컬에서 작업 전에 pull을 하는 것은 자연스러운 흐름이고 좋은 습관이라고 생각합니다.
* 문제별로 브랜치를 구분하는 것은 말씀하신대로 너무 PR을 자주 하게 되어 번거롭겠습니다. 주차별로 브랜치를 구분해도 괜찮을 것 같습니다.
* 번거로우셨을텐데 테스트를 해주셔서 감사합니다.

**Comment by YunWonYong** [comment]
네 알겠습니다.
그럼 제가 정리하도록 하겠습니다,
